version: 1.0.{build}.0
clone_folder: c:\projects\$(APPVEYOR_PROJECT_NAME)
environment:
  ApplicationID:
    secure: IJBqnB6WjtDi3ej/zy2D70Ry1AvJOrlZK5BhSoqEdxNENd0CL9qdMJndbi6p+di3
  ApplicationPassword:
    secure: b8lT719n/ll0Bp5SloBvzw==
  TenantID:
    secure: J/my7xsOE9jewR0DDhD+EU5jeo5Bp83/nmIK8a8QI0QLoZXStCOtk1vUjVsKylW2
matrix:
  fast_finish: true
install:
  - git clone https://github.com/Microsoft/DscConfiguration.Tests
  - ps: |
        Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.205 -Force | Out-Null
        Install-Module Invoke-Build -force
build_script:
  - ps: |
        Invoke-Build
notifications:
  -provider: Email
    to: {APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL}
    subject: 'Build {{status}}'
    message: "{{message}}, {{commitId}}"