#---------------------------------#
#      environment configuration  #
#---------------------------------#
version: 1.0.{build}.0
environment:
  AppID:
    secure: IJBqnB6WjtDi3ej/zy2D70Ry1AvJOrlZK5BhSoqEdxNENd0CL9qdMJndbi6p+di3
  AppPass:
    secure: b8lT719n/ll0Bp5SloBvzw==
  Tenant:
    secure: J/my7xsOE9jewR0DDhD+EU5jeo5Bp83/nmIK8a8QI0QLoZXStCOtk1vUjVsKylW2
install:
  - git clone https://github.com/Microsoft/WindowsDNSServer.Config
  - git clone https://github.com/PowerShell/DscResource.Tests
  - ps: |
        Import-Module -Name .\DscResource.Tests\TestHelper.psm1 -Force
        Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.205 -Force | Out-Null
        Install-Module -Name Pester -Repository PSGallery -Force
        Install-Module -Name AzureRM -Repository PSGallery -Force
        
#---------------------------------#
#      build configuration        #
#---------------------------------#

build: false

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
    - ps: |
        # Suppressing tests until configuration test helper is created
        # $testResultsFile = ".\TestsResults.xml"
        # $res = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru
        # (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
        # if ($res.FailedCount -gt 0) {
        #     throw "$($res.FailedCount) tests failed."
        # }

#---------------------------------# 
#      deployment configuration   # 
#---------------------------------# 

# scripts to run before deployment 
deploy_script: 
  - ps: |
        # Correct duplicates in AppVeyor environment psmodulepath
        foreach($path in $env:psmodulepath.split(';').ToUpper().ToLower())
        {
          [array]$correctDirFormat += "$path\;"
        }
        $correctDirFormat = $correctDirFormat.replace("\\","\") | ? {$_ -ne '\;'} | Select-Object -Unique
        foreach ($path in $correctDirFormat.split(';'))
        {
          [string]$fixPath += "$path;"
        }
        $env:psmodulepath = $fixpath.replace(';;',';')
        $env:psmodulepath = $env:psmodulepath+'c:\projects;'
        
        
        # Load module data and create array of objects containing prerequisite details
        $RequiredModules = (Import-PowerShellDataFile -Path (".\" + $env:APPVEYOR_PROJECT_NAME + ".psd1")).RequiredModules
        foreach($RequiredModule in $RequiredModules) {
          # Install latest if no version is specified
          if ($RequiredModule.gettype().Name -eq 'String')
          {
            if (Find-Module -Name $RequiredModule)
            {
              Install-Module -Name $RequiredModule -force
            }
          }
          # Install specific version if specified
          if ($RequiredModule.gettype().Name -eq 'Hashtable')
          {
            if (Find-Module -Name $RequiredModule.ModuleName -RequiredVersion $RequiredModule.ModuleVersion)
            { 
              Install-Module -Name $RequiredModule.ModuleName -RequiredVersion $RequiredModule.ModuleVersion -force
            }
          }
        }
        
        # Import Configuration module DEBUGGING
        $ModuleDir = New-Item -Type Folder -Path $env:ProgramFiles\WindowsPowerShell\Modules\$env:APPVEYOR_PROJECT_NAME -force
        Copy-Item -Path .\$env:APPVEYOR_PROJECT_NAME.psd1 -Destination $ModuleDir -force
        Copy-Item -Path .\$env:APPVEYOR_PROJECT_NAME.psm1 -Destination $ModuleDir -force
        Import-Module -Name $env:APPVEYOR_PROJECT_NAME

        # Log in to Azure
        $loc = 'eastus2'
        $creds = New-Object -typename System.Management.Automation.PSCredential -argumentlist $env:AppID, $(convertto-securestring -String $env:AppPass -AsPlainText -Force)
        
        # Suppress request to share usage information
        if (!(Resolve-Path -Path 'C:\Users\appveyor\AppData\Roaming\Windows Azure Powershell\' -ErrorAction SilentlyContinue))
        {
          mkdir 'C:\Users\appveyor\AppData\Roaming\Windows Azure Powershell\' | Out-Null
        }
        Set-Content -Value '{"enableAzureDataCollection":true}' -Path 'C:\Users\appveyor\AppData\Roaming\Windows Azure Powershell\AzureDataCollectionProfile.json' | Out-Null
        
        Add-AzureRmAccount -Credential $creds -ServicePrincipal -TenantId $env:Tenant | Out-Null
        
        # Create Resource Group
        if (!(Get-AzureRmResourceGroup -Name $env:APPVEYOR_PROJECT_NAME -ErrorAction SilentlyContinue))
        {
            New-AzureRmResourceGroup -Name $env:APPVEYOR_PROJECT_NAME -Location $loc | Out-Null
        }
        
        # Create Azure Automation account
        if (!(Get-AzureRMAutomationAccount -ResourceGroupName $env:APPVEYOR_PROJECT_NAME -Name $env:APPVEYOR_PROJECT_ID -ErrorAction SilentlyContinue))
        {
          New-AzureRMAutomationAccount -ResourceGroupName $env:APPVEYOR_PROJECT_NAME -Name $env:APPVEYOR_PROJECT_ID -Location $loc | Out-Null
        }

        # Upload required DSC resources
        foreach($automationModuleToUpload in $requiredModules) {
          if (!(Get-AzureRMAutomationModule -ResourceGroupName $env:APPVEYOR_PROJECT_NAME -AutomationAccountName $env:APPVEYOR_PROJECT_ID -Name $automationModuleToUpload.Name -ErrorAction SilentlyContinue))
          {
            New-AzureRMAutomationModule -ResourceGroupName $env:APPVEYOR_PROJECT_NAME -AutomationAccountName $env:APPVEYOR_PROJECT_ID -Name $automationModuleToUpload.Name -ContentLink $automationModuleToUpload.URI | Out-Null 
          }
        }

        # Discover configurations from module
        $Configurations = Get-Command -module $env:APPVEYOR_PROJECT_NAME -Type Configuration
        
        # Create configuration scripts and import to Azure Automation
        foreach ($confToCompile in $Configurations) {
          
          $confName = $confToCompile.Name
          $confConfigData = Import-PowerShellDataFile ".\ConfigurationData\$confToCompileName.ConfigData.psd1" -ErrorAction SilentlyContinue
          
          # Create working folder
          New-Item -Path C:\DSC -ItemType Directory -ErrorAction SilentlyContinue | Out-Null
          
          # Create one script per configuration with matching name
          if ($Config = (Get-Command $confName).ScriptBlock)
          {
            "Configuration $confName`n{" | Out-File "C:\DSC\$confName.ps1"
            $Config | Out-File "C:\DSC\$confName.ps1" -Append
            "}`n" | Out-File "C:\DSC\$confName.ps1" -Append

            # Import
            if (Import-AzureRmAutomationDscConfiguration -ResourceGroupName $env:APPVEYOR_PROJECT_NAME -AutomationAccountName $env:APPVEYOR_PROJECT_ID -SourcePath "C:\DSC\$confName.ps1" -Published -Force | Out-Null)
            {
              Start-AzureRmAutomationDscCompilationJob -ResourceGroupName $env:APPVEYOR_PROJECT_NAME -AutomationAccountName $env:APPVEYOR_PROJECT_ID -ConfigurationName $confName -ConfigurationData $confConfigData | Out-Null
            }
          }
          else 
          {
            Write-Error 'No configuration was loaded.'
          }
        }
        
        # TODO - handle no configdata through splatting
        # TODO - eliminate local compile
        # TODO - standardize approach to deploying ARM template from repo handing off config name as param        
        # TODO - MVP is single VM, complete is multiple VM solution
        # TODO - tests from demo_ci
        
        Start-Sleep 600
        Remove-AzureRmResourceGroup -Name $env:APPVEYOR_PROJECT_NAME -Force
